//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.0
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MANAGER.Localisation.Language {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalisationFr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalisationFr() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MANAGER.Localisation.Language.LocalisationFr", typeof(LocalisationFr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        public static string ActiveLangage {
            get {
                return ResourceManager.GetString("ActiveLangage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Price.
        /// </summary>
        public static string All_Price {
            get {
                return ResourceManager.GetString("All_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quantity.
        /// </summary>
        public static string All_QTE {
            get {
                return ResourceManager.GetString("All_QTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to connect to the database.
        /// </summary>
        public static string Box_DBFail {
            get {
                return ResourceManager.GetString("Box_DBFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        public static string Box_Error {
            get {
                return ResourceManager.GetString("Box_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cost estimate successfully added.
        /// </summary>
        public static string Box_Success {
            get {
                return ResourceManager.GetString("Box_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The cost estimate number &quot;{0}&quot; was successfully added to the database. The total cost is {1}€.
        /// </summary>
        public static string Box_SuccessAdd {
            get {
                return ResourceManager.GetString("Box_SuccessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        public static string BTN_Add {
            get {
                return ResourceManager.GetString("BTN_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create.
        /// </summary>
        public static string BTN_Create {
            get {
                return ResourceManager.GetString("BTN_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a customer :.
        /// </summary>
        public static string DC_ChooseCustomer {
            get {
                return ResourceManager.GetString("DC_ChooseCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cost estimate n° {0} - Date : {1} - Total : {2}€.
        /// </summary>
        public static string DC_ComboBoxCustomer {
            get {
                return ResourceManager.GetString("DC_ComboBoxCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quantity Commanded : {0}.
        /// </summary>
        public static string DC_Command {
            get {
                return ResourceManager.GetString("DC_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à His costs estimate :.
        /// </summary>
        public static string DC_CustomerCE {
            get {
                return ResourceManager.GetString("DC_CustomerCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete this customer.
        /// </summary>
        public static string DC_DeleteCustomer {
            get {
                return ResourceManager.GetString("DC_DeleteCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The merchandise :.
        /// </summary>
        public static string DM_Merchandise {
            get {
                return ResourceManager.GetString("DM_Merchandise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quantity in stock : {0}.
        /// </summary>
        public static string DM_Stock {
            get {
                return ResourceManager.GetString("DM_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a merchandise.
        /// </summary>
        public static string EC_AddMerchandise {
            get {
                return ResourceManager.GetString("EC_AddMerchandise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a cost estimate.
        /// </summary>
        public static string EC_CreateCE {
            get {
                return ResourceManager.GetString("EC_CreateCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete the merchandise.
        /// </summary>
        public static string EC_DeleteMerchandise {
            get {
                return ResourceManager.GetString("EC_DeleteMerchandise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        public static string Link_About {
            get {
                return ResourceManager.GetString("Link_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apparence.
        /// </summary>
        public static string Link_Apparence {
            get {
                return ResourceManager.GetString("Link_Apparence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cost Estimate.
        /// </summary>
        public static string Link_CE {
            get {
                return ResourceManager.GetString("Link_CE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a new cost estimate.
        /// </summary>
        public static string Link_CreateCE {
            get {
                return ResourceManager.GetString("Link_CreateCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a new customer to the database.
        /// </summary>
        public static string Link_CreateCustomer {
            get {
                return ResourceManager.GetString("Link_CreateCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a new merchandise to the database.
        /// </summary>
        public static string Link_CreateMerchandise {
            get {
                return ResourceManager.GetString("Link_CreateMerchandise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Customer.
        /// </summary>
        public static string Link_Customer {
            get {
                return ResourceManager.GetString("Link_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display every cost estimate.
        /// </summary>
        public static string Link_DisplayCE {
            get {
                return ResourceManager.GetString("Link_DisplayCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display every active customer.
        /// </summary>
        public static string Link_DisplayCustomer {
            get {
                return ResourceManager.GetString("Link_DisplayCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display every merchandise.
        /// </summary>
        public static string Link_DisplayMerchandise {
            get {
                return ResourceManager.GetString("Link_DisplayMerchandise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merchandise.
        /// </summary>
        public static string Link_Merchandise {
            get {
                return ResourceManager.GetString("Link_Merchandise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parameters.
        /// </summary>
        public static string Link_Param {
            get {
                return ResourceManager.GetString("Link_Param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select your language : .
        /// </summary>
        public static string PM_SelectLanguage {
            get {
                return ResourceManager.GetString("PM_SelectLanguage", resourceCulture);
            }
        }
    }
}
